jenkins:

  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: ${JENKINS_ADMIN_ID}
         password: ${JENKINS_ADMIN_PASSWORD}
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:admin"
        - "Overall/Read:authenticated"
unclassified:
  location:
    url: http://localhost:80
jobs:
    - script: >
        pipelineJob("Pipeline to seed or update all pipelines") {
        definition {
            cpsScm {
                scm {
                    git{
                      remote {
                        url("https://github.com/Moeezulhaq/Jenkins_Jcasc.git")
                      }
                      branch("*/master")
                    }                                       
                }
            }
          }
        }
  # remotingSecurity:
  #   enabled: true
security:
  queueItemAuthenticator:
    authenticators:
    - global:
        strategy: triggeringUsersAuthorizationStrategy 

credentials:
  system:
    domainCredentials:
      - credentials:
          - string:
              scope: GLOBAL
              id: slack-token
              secret: '${SLACK_TOKEN}'
              description: Slack token

unclassified:
  slackNotifier:
    teamDomain: eurustechnologies # i.e. your-company (just the workspace name not the full url)
    tokenCredentialId: slack-token
  awsCredentialsProvider:
    # cache: (boolean)           # optional
    # endpointConfiguration:     # optional
    #   serviceEndpoint: (URL)
    #   signingRegion: us-east-1
    listSecrets:               # optional
      filters:
        - key: tag-key
          values:
            - "Name"
        - key: tag-value
          values:
            - "slack_token_moeez"